sudo: false
language: cpp

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - doxygen
      - graphviz

before_script: skip
# Nothing to do

script:
  - doxygen $TRAVIS_BUILD_DIR/Doxyfile
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 ./ci-build.sh -v $TRAVIS_BUILD_NUMBER -r -p deb

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_PAGES_TOKEN
    keep-history: true
    local_dir: docs
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: curl -T packages/release/libsock_connect-0.1.$TRAVIS_BUILD_NUMBER-1-x86_64.deb -udgolgovsky:$BINTRAY_API_KEY "https://api.bintray.com/content/dgolgovsky/own/sock_connect/$TRAVIS_BUILD_NUMBER/libsock_connect-0.1.$TRAVIS_BUILD_NUMBER-1-x86_64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
