sudo: false
language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - graphviz

before_script: skip
# Nothing to do

script:
  - doxygen $TRAVIS_BUILD_DIR/Doxyfile
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc ./ci-build.sh -p deb -v $TRAVIS_BUILD_NUMBER -b

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_PAGES_TOKEN
    keep-history: true
    local_dir: docs
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: curl -T packages/build/libsock_connect-0.$TRAVIS_BUILD_NUMBER-1-x86_64.deb -udgolgovsky:$BINTRAY_API_KEY "https://api.bintray.com/content/dgolgovsky/own/sock_connect/$TRAVIS_BUILD_NUMBER/libsock_connect-0.$TRAVIS_BUILD_NUMBER-1-x86_64.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
