.TH "tests/catch_test/catch-test.cpp" 3 "Mon Nov 16 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/catch_test/catch-test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <catch\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Input 0','[none]')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.PP
Definition at line 1 of file catch\-test\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Input 0', ''[none])"

.PP
Definition at line 4 of file catch\-test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
