.TH "Connector< Type >" 3 "Mon Nov 18 2019" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connector< Type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sock_connect\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > \fBConnector\fP (const T addr, U port)"
.br
.ti -1c
.RI "\fB~Connector\fP ()=default"
.br
.ti -1c
.RI "int \fBAccept\fP ()"
.br
.ti -1c
.RI "bool \fBListen\fP () const "
.br
.ti -1c
.RI "bool \fBBind\fP (bool listen=false) const "
.br
.ti -1c
.RI "template<typename T > ssize_t \fBSend\fP (const T *value, std::size_t size)"
.br
.ti -1c
.RI "template<typename T > ssize_t \fBReceive\fP (T *value, std::size_t size)"
.br
.ti -1c
.RI "int \fBConnect\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP (int \fBid\fP=0)"
.br
.ti -1c
.RI "void \fBsetRTS\fP ()"
.br
.ti -1c
.RI "void \fBclrRTS\fP ()"
.br
.ti -1c
.RI "int \fBid\fP ()"
.br
.ti -1c
.RI "bool \fBstatus\fP () const "
.br
.ti -1c
.RI "void \fBassign_client\fP (int \fBid\fP=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Type>
.br
class Connector< Type >"

.PP
Definition at line 10 of file sock_connect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Type > template<typename T , typename U > \fBConnector\fP< Type >::\fBConnector\fP (const T addr, U port)\fC [inline]\fP"

.PP
Definition at line 17 of file sock_connect\&.h\&.
.SS "template<class Type > \fBConnector\fP< Type >::~\fBConnector\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class Type > int \fBConnector\fP< Type >::Accept ()\fC [inline]\fP"

.PP
Definition at line 20 of file sock_connect\&.h\&.
.SS "template<class Type > void \fBConnector\fP< Type >::assign_client (int id = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 43 of file sock_connect\&.h\&.
.SS "template<class Type > bool \fBConnector\fP< Type >::Bind (bool listen = \fCfalse\fP) const\fC [inline]\fP"

.PP
Definition at line 22 of file sock_connect\&.h\&.
.SS "template<class Type > void \fBConnector\fP< Type >::clrRTS ()\fC [inline]\fP"

.PP
Definition at line 38 of file sock_connect\&.h\&.
.SS "template<class Type > int \fBConnector\fP< Type >::Connect ()\fC [inline]\fP"

.PP
Definition at line 34 of file sock_connect\&.h\&.
.SS "template<class Type > int \fBConnector\fP< Type >::id ()\fC [inline]\fP"

.PP
Definition at line 40 of file sock_connect\&.h\&.
.SS "template<class Type > bool \fBConnector\fP< Type >::Listen () const\fC [inline]\fP"

.PP
Definition at line 21 of file sock_connect\&.h\&.
.SS "template<class Type > template<typename T > ssize_t \fBConnector\fP< Type >::Receive (T * value, std::size_t size)\fC [inline]\fP"

.PP
Definition at line 30 of file sock_connect\&.h\&.
.SS "template<class Type > template<typename T > ssize_t \fBConnector\fP< Type >::Send (const T * value, std::size_t size)\fC [inline]\fP"

.PP
Definition at line 25 of file sock_connect\&.h\&.
.SS "template<class Type > void \fBConnector\fP< Type >::setRTS ()\fC [inline]\fP"

.PP
Definition at line 37 of file sock_connect\&.h\&.
.SS "template<class Type > void \fBConnector\fP< Type >::Shutdown (int id = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 35 of file sock_connect\&.h\&.
.SS "template<class Type > bool \fBConnector\fP< Type >::status () const\fC [inline]\fP"

.PP
Definition at line 41 of file sock_connect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
