.TH "src/Connection.cpp" 3 "Tue Sep 15 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Connection.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Connection\&.h'\fP
.br
\fC#include 'type_name\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
