.TH "src/Connection.cpp" 3 "Thu Jul 9 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Connection.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Connection\&.h'\fP
.br
\fC#include 'type_name\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBip_to_int\fP (std::string const &str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int ip_to_int (std::string const & str)"
Transform <const char*> IP-address to uint32_t '127\&.0\&.0\&.1' -> 0x7f000001 
.PP
Definition at line 8 of file Connection\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
