.TH "SocketIp" 3 "Mon Nov 16 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketIp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SocketIp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocketIp\fP (\fBconn_type\fP ct)"
.br
.ti -1c
.RI "\fBSocketIp\fP (int socket_id)"
.br
.ti -1c
.RI "\fBSocketIp\fP (\fBSocketIp\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBSocketIp\fP (const \fBSocketIp\fP &)=delete"
.br
.ti -1c
.RI "\fBSocketIp\fP & \fBoperator=\fP (const \fBSocketIp\fP &)=delete"
.br
.ti -1c
.RI "\fBSocketIp\fP & \fBoperator=\fP (\fBSocketIp\fP &&)=delete"
.br
.ti -1c
.RI "\fB~SocketIp\fP ()"
.br
.ti -1c
.RI "int \fBid\fP () const noexcept"
.br
.ti -1c
.RI "std::string \fBc_type\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file SocketIp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SocketIp::SocketIp (\fBconn_type\fP ct)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 59 of file SocketIp\&.h\&.
.SS "SocketIp::SocketIp (int socket_id)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 81 of file SocketIp\&.h\&.
.SS "SocketIp::SocketIp (\fBSocketIp\fP && other)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 84 of file SocketIp\&.h\&.
.SS "SocketIp::SocketIp (const \fBSocketIp\fP &)\fC [delete]\fP"

.SS "SocketIp::~SocketIp ()\fC [inline]\fP"

.PP
Definition at line 95 of file SocketIp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string SocketIp::c_type () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 105 of file SocketIp\&.h\&.
.SS "int SocketIp::id () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 101 of file SocketIp\&.h\&.
.SS "\fBSocketIp\fP& SocketIp::operator= (const \fBSocketIp\fP &)\fC [delete]\fP"

.SS "\fBSocketIp\fP& SocketIp::operator= (\fBSocketIp\fP &&)\fC [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
