.TH "src/sock_connect.h" 3 "Thu Jun 18 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sock_connect.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TCP\&.h'\fP
.br
\fC#include 'UDP\&.h'\fP
.br
\fC#include 'UNIX\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnector< Type >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
