.TH "include/type_name.h" 3 "Thu Dec 10 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/type_name.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <cxxabi\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > std::string \fBtype_name\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T > std::string type_name ()"

.PP
Definition at line 14 of file type_name\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
