.TH "UDP" 3 "Mon Nov 18 2019" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDP \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UDP\&.h>\fP
.PP
Inherits \fBConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUDP\fP (uint32_t address, uint16_t port)"
.br
.ti -1c
.RI "\fBUDP\fP (const char *address, uint16_t port)"
.br
.ti -1c
.RI "\fB~UDP\fP () override"
.br
.ti -1c
.RI "template<typename T , typename S > ssize_t \fBReceive\fP (T *value, S const tu_size)"
.br
.RI "\fIReceive int, \fBUDP\fP Virtual receiving function for int values as \fBUDP\fP connections without size\&. \fP"
.ti -1c
.RI "template<typename T , typename S > ssize_t \fBSend\fP (T const *value, S const tu_size)"
.br
.RI "\fISend int value Virtual sending function for int values\&. \fP"
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (uint8_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (uint16_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (uint32_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (std::string *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (char *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (const uint8_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (const uint16_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (const uint32_t *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (const std::string *value, const std::size_t tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (const char *value, const std::size_t tu_size)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file UDP\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UDP::UDP (uint32_t address, uint16_t port)\fC [explicit]\fP"

.PP
Definition at line 7 of file UDP\&.cpp\&.
.SS "UDP::UDP (const char * address, uint16_t port)\fC [explicit]\fP"

.PP
Definition at line 17 of file UDP\&.cpp\&.
.SS "UDP::~UDP ()\fC [override]\fP"

.PP
Definition at line 27 of file UDP\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename S > ssize_t UDP::Receive (T * value, S const tu_size)"

.PP
Receive int, \fBUDP\fP Virtual receiving function for int values as \fBUDP\fP connections without size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.br
\fItu_size\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
message size 
.RE
.PP

.SS "template<> ssize_t UDP::Receive (uint8_t * value, const std::size_t tu_size)"

.PP
Definition at line 32 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Receive (uint16_t * value, const std::size_t tu_size)"

.PP
Definition at line 47 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Receive (uint32_t * value, const std::size_t tu_size)"

.PP
Definition at line 62 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Receive (std::string * value, const std::size_t tu_size)"

.PP
Definition at line 77 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Receive (char * value, const std::size_t tu_size)"

.PP
Definition at line 94 of file UDP\&.cpp\&.
.SS "template<typename T , typename S > ssize_t UDP::Send (T const * value, S const tu_size)"

.PP
Send int value Virtual sending function for int values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.br
\fItu_size\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
message size 
.RE
.PP

.SS "template<> ssize_t UDP::Send (const uint8_t * value, const std::size_t tu_size)"

.PP
Definition at line 102 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Send (const uint16_t * value, const std::size_t tu_size)"

.PP
Definition at line 118 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Send (const uint32_t * value, const std::size_t tu_size)"

.PP
Definition at line 134 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Send (const std::string * value, const std::size_t tu_size)"

.PP
Definition at line 150 of file UDP\&.cpp\&.
.SS "template<> ssize_t UDP::Send (const char * value, const std::size_t tu_size)"

.PP
Definition at line 166 of file UDP\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
