.TH "tests/udp_socket_test.cpp" 3 "Mon Nov 16 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/udp_socket_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sock_connect\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBserver\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 23 of file udp_socket_test\&.cpp\&.
.SS "void server ()"

.PP
Definition at line 4 of file udp_socket_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
