.TH "UNIX" 3 "Fri Jul 3 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UNIX\&.h>\fP
.PP
Inherits \fBConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUNIX\fP (std::string const &path)"
.br
.ti -1c
.RI "\fBUNIX\fP (char const *path)"
.br
.ti -1c
.RI "\fB~UNIX\fP () override"
.br
.ti -1c
.RI "template<typename T > ssize_t \fBReceive\fP (T *value, std::size_t tu_size)"
.br
.RI "\fIReceive value Virtual receiving function for values\&. \fP"
.ti -1c
.RI "template<typename T > ssize_t \fBSend\fP (T const *value, std::size_t tu_size)"
.br
.RI "\fISend value Virtual sending function for values\&. \fP"
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (std::string *value, std::size_t const tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (std::string const *value, std::size_t const tu_size)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file UNIX\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UNIX::UNIX (std::string const & path)\fC [explicit]\fP"

.PP
Definition at line 4 of file UNIX\&.cpp\&.
.SS "UNIX::UNIX (char const * path)\fC [explicit]\fP"

.PP
Definition at line 14 of file UNIX\&.cpp\&.
.SS "UNIX::~UNIX ()\fC [override]\fP"

.PP
Definition at line 24 of file UNIX\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > template ssize_t UNIX::Receive (T * value, std::size_t tu_size)"

.PP
Receive value Virtual receiving function for values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.br
\fItu_size\fP Package size\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
message size 
.RE
.PP

.PP
Definition at line 33 of file UNIX\&.cpp\&.
.SS "template<> ssize_t UNIX::Receive (std::string * value, std::size_t const tu_size)"

.PP
Definition at line 117 of file UNIX\&.cpp\&.
.SS "template<typename T > template ssize_t UNIX::Send (T const * value, std::size_t tu_size)"

.PP
Send value Virtual sending function for values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.br
\fItu_size\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
message size 
.RE
.PP

.PP
Definition at line 61 of file UNIX\&.cpp\&.
.SS "template<> ssize_t UNIX::Send (std::string const * value, std::size_t const tu_size)"

.PP
Definition at line 126 of file UNIX\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
