.TH "USB" 3 "Thu Jun 25 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <USB\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSB\fP (std::string address, speed_t speed)"
.br
.ti -1c
.RI "\fB~USB\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.ti -1c
.RI "template<typename T > ssize_t \fBReceive\fP (T *value, std::size_t const tu_size)"
.br
.ti -1c
.RI "template<typename T > ssize_t \fBSend\fP (T const *value, std::size_t const tu_size)"
.br
.ti -1c
.RI "void \fBsetRTS\fP () const "
.br
.ti -1c
.RI "void \fBclrRTS\fP () const "
.br
.ti -1c
.RI "int \fBid\fP () const "
.br
.ti -1c
.RI "bool \fBstatus\fP () const "
.br
.ti -1c
.RI "template<> ssize_t \fBReceive\fP (std::string *value, std::size_t const tu_size)"
.br
.ti -1c
.RI "template<> ssize_t \fBSend\fP (std::string const *value, std::size_t const tu_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBstate\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file USB\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "USB::USB (std::string address, speed_t speed)\fC [explicit]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP path to device {/dev/ttyACM0 | /dev/ttyUSB0} 
.br
\fIspeed\fP connection speed: B9600, B57600, B115200 
.RE
.PP

.PP
Definition at line 7 of file USB\&.cpp\&.
.SS "USB::~USB ()"

.PP
Definition at line 10 of file USB\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void USB::clrRTS () const"

.PP
Definition at line 171 of file USB\&.cpp\&.
.SS "bool USB::Connect ()"
Connect/open port CONFIGURE THE UART The flags (defined in /usr/include/termios\&.h - see http://pubs.opengroup.org/onlinepubs/007908799/xsh/termios.h.html):
.PP
Baud rate:- B1200, B2400, B4800, B9600, B19200, B38400, B57600, B115200, B230400, B460800, B500000, B576000, B921600, B1000000, B1152000, B1500000, B2000000, B2500000, B3000000, B3500000, B4000000
.PP
CSIZE:- CS5, CS6, CS7, CS8 CLOCAL - Ignore modem status lines CREAD - Enable receiver IGNPAR = Ignore characters with parity errors ICRNL - Map CR to NL on input (Use for ASCII comms where you want to auto correct end of line characters - don't use for bianry comms!) PARENB - Parity enable PARODD - Odd parity (else even)
.PP
Definition at line 14 of file USB\&.cpp\&.
.SS "int USB::id () const"

.PP
Definition at line 182 of file USB\&.cpp\&.
.SS "template<typename T > template ssize_t USB::Receive (T * value, std::size_t const tu_size)"

.PP
Definition at line 61 of file USB\&.cpp\&.
.SS "template<> ssize_t USB::Receive (std::string * value, std::size_t const tu_size)"

.PP
Definition at line 145 of file USB\&.cpp\&.
.SS "template<typename T > template ssize_t USB::Send (T const * value, std::size_t const tu_size)"

.PP
Definition at line 89 of file USB\&.cpp\&.
.SS "template<> ssize_t USB::Send (std::string const * value, std::size_t const tu_size)"

.PP
Definition at line 154 of file USB\&.cpp\&.
.SS "void USB::setRTS () const"

.PP
Definition at line 164 of file USB\&.cpp\&.
.SS "void USB::Shutdown ()"

.PP
Definition at line 158 of file USB\&.cpp\&.
.SS "bool USB::status () const"

.PP
Definition at line 178 of file USB\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool USB::state {false}"

.PP
Definition at line 16 of file USB\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
