.TH "USB" 3 "Mon Nov 16 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <USB\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSB\fP (const std::string &address, speed_t speed)"
.br
.ti -1c
.RI "\fBUSB\fP (const char *address, speed_t speed)"
.br
.ti -1c
.RI "\fB~USB\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP (int \fBid\fP)"
.br
.ti -1c
.RI "template<typename T > std::size_t \fBReceive\fP (T *value, std::size_t tu_size)"
.br
.RI "\fIReceive value Virtual receiving function for values\&. \fP"
.ti -1c
.RI "template<typename T > std::size_t \fBSend\fP (T const *value, std::size_t tu_size)"
.br
.RI "\fISend value Virtual sending function for values\&. \fP"
.ti -1c
.RI "bool \fBstatus\fP () const "
.br
.ti -1c
.RI "int \fBid\fP () const "
.br
.ti -1c
.RI "int \fBAccept\fP (const std::string &) const "
.br
.ti -1c
.RI "bool \fBListen\fP () const "
.br
.ti -1c
.RI "bool \fBBind\fP () const "
.br
.ti -1c
.RI "void \fBassign_thread\fP (int \fBid\fP) const "
.br
.ti -1c
.RI "template<> std::size_t \fBReceive\fP (std::string *value, std::size_t const tu_size)"
.br
.ti -1c
.RI "template<> std::size_t \fBSend\fP (std::string const *value, std::size_t const tu_size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file USB\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "USB::USB (const std::string & address, speed_t speed)\fC [explicit]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP path to device {/dev/ttyACM0 | /dev/ttyUSB0} 
.br
\fIspeed\fP connection m_speed: B9600, B57600, B115200 
.RE
.PP

.PP
Definition at line 4 of file USB\&.cpp\&.
.SS "USB::USB (const char * address, speed_t speed)\fC [explicit]\fP"

.PP
Definition at line 17 of file USB\&.cpp\&.
.SS "USB::~USB ()"

.PP
Definition at line 30 of file USB\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int USB::Accept (const std::string &) const"

.PP
Definition at line 229 of file USB\&.cpp\&.
.SS "void USB::assign_thread (int id) const"

.PP
Definition at line 216 of file USB\&.cpp\&.
.SS "bool USB::Bind () const"

.PP
Definition at line 239 of file USB\&.cpp\&.
.SS "bool USB::Connect ()"
Connect/open port CONFIGURE THE UART The flags (defined in /usr/include/termios\&.h - see http://pubs.opengroup.org/onlinepubs/007908799/xsh/termios.h.html):
.PP
Baud rate:- B1200, B2400, B4800, B9600, B19200, B38400, B57600, B115200, B230400, B460800, B500000, B576000, B921600, B1000000, B1152000, B1500000, B2000000, B2500000, B3000000, B3500000, B4000000
.PP
CSIZE:- CS5, CS6, CS7, CS8 CLOCAL - Ignore modem Status lines CREAD - Enable receiver IGNPAR = Ignore characters with parity errors ICRNL - Map CR to NL on input (Use for ASCII comms where you want to auto correct end of line characters - don't use for bianry comms!) PARENB - Parity enable PARODD - Odd parity (else even)
.PP
Definition at line 39 of file USB\&.cpp\&.
.SS "int USB::id () const"
Current here for compability Do the same as get_descriptor 
.PP
\fBReturns:\fP
.RS 4
fd 
.RE
.PP

.PP
Definition at line 225 of file USB\&.cpp\&.
.SS "bool USB::Listen () const"

.PP
Definition at line 249 of file USB\&.cpp\&.
.SS "template<typename T > template std::size_t USB::Receive (T * value, std::size_t tu_size)"

.PP
Receive value Virtual receiving function for values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Address of value to receive 
.br
\fItu_size\fP Bytes to receive 
.RE
.PP
\fBReturns:\fP
.RS 4
Count of received bytes 
.RE
.PP

.PP
Definition at line 87 of file USB\&.cpp\&.
.SS "template<> std::size_t USB::Receive (std::string * value, std::size_t const tu_size)"

.PP
Definition at line 169 of file USB\&.cpp\&.
.SS "template<typename T > template std::size_t USB::Send (T const * value, std::size_t tu_size)"

.PP
Send value Virtual sending function for values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Address of value to send 
.br
\fItu_size\fP Bytes to send 
.RE
.PP
\fBReturns:\fP
.RS 4
Count of sent bytes 
.RE
.PP

.PP
Definition at line 113 of file USB\&.cpp\&.
.SS "template<> std::size_t USB::Send (std::string const * value, std::size_t const tu_size)"

.PP
Definition at line 175 of file USB\&.cpp\&.
.SS "void USB::Shutdown ()"

.PP
Definition at line 179 of file USB\&.cpp\&.
.SS "void USB::Shutdown (int id)"

.PP
Definition at line 190 of file USB\&.cpp\&.
.SS "bool USB::status () const"

.PP
Definition at line 208 of file USB\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
