.TH "tests/usb_socket_test.cpp" 3 "Thu Dec 10 2020" "Version 01" "Shared library Connection Socket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/usb_socket_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sock_connect\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmain_loop\fP (const std::string &dev_path, speed_t speed)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 31 of file usb_socket_test\&.cpp\&.
.SS "bool main_loop (const std::string & dev_path, speed_t speed)\fC [inline]\fP"

.PP
Definition at line 5 of file usb_socket_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared library Connection Socket from the source code\&.
